/**
 * Created by jono on 12/29/14.
 */
var constants = {
	PX: "px",
	POST: "POST",
	CLK: "click",
	CHECK: "check",
	DELIVERY: "delivery",
	PICKUP: "pickup",
	UNCHECK: "uncheck",
	UNDEF: "undefined",
	MOUSEOVER: "mouseover",
	HOVER: "hover",
	MOUSEENTER: "mouseenter",
	MOUSEOUT: "mouseout",
	HIDE: 0,
	SHOW: 1,
	DS: "/",
	BODY: "body",
	ORDER_SPACER_FACTOR: 0.45,
	MENU_SPACER_FACTOR: 0.15,
	MENU: "menu",
	DATABASE: "database",
	SESSION: "session",
	UPDATE_DB: "update_database",
	UPDATE_SESSION: "update_session",
	OPT: "opt",
	CANCEL: "cancel",
	ORB_CARD_REFRESH: "orb_card_refresh",
	ORDER_FORM_UPDATE: "order_form_update",
	ORDER_UI_UPDATE: "order_ui_update",
	F: "",
	D: "<span class='icon-double tiny-opt icon-hnj-inline'></span>",
	R: "<span class='icon-right-side tiny-opt icon-hnj-inline'></span>",
	L: "<span class='icon-left-side tiny-opt icon-hnj-inline'></span>",
	ORDER: "order",
	PRIMARY: "primary",
	SPLASH: "splash",
	FLASH: "flash",
	WEIGHT: "weight",
	REM: 16,
	STASH:1,
	OL:3,
	STASH_OL:4,
	STOP:5,
	STASH_STOP: 6,
	STOP_OL:8,
	STASH_OL_STOP:9
};

var C = constants;